
create table user (
    id integer generated by default as identity (start with 1) primary key,
    name varchar(45) not null,
    logInId varchar(45) not null,
    password varchar(45) not null,
    role varchar(45) not null,
    createdOn datetime not null,
    modifiedOn datetime not null,
    createdBy varchar(45) not null,
    modifiedBy varchar(45) not null
);

insert into user(id,name,logInId,password,role,createdOn,modifiedOn,createdBy,modifiedBy) values
    (1,'admin','admin','admin','ADMIN','2012-06-02 00:00:00','2012-06-02 00:00:00','admin','admin'),
    (2,'guest','guest','guest','GUEST','2012-06-02 00:00:00','2012-06-02 00:00:00','admin','admin');

create table companyterms (
    id integer generated by default as identity (start with 1) primary key,
    terms varchar(5000),
    companyAddress varchar(500),
    companyName varchar(45),
    companyPhone varchar(45),
    companyEmail varchar(45),
    companyWebsite varchar(45),
    vat_tin varchar(45),
    cst_tin varchar(45),
    createdOn datetime not null,
    modifiedOn datetime,
    createdBy varchar(45) not null,
    modifiedBy varchar(45)
);
insert into companyterms (id, terms, companyAddress, createdOn, modifiedOn, createdBy, modifiedBy) values
(1, 'terms', 'my company','2012-06-02 00:00:00','2012-06-02 00:00:00','admin','admin');

create table customer (
    id integer generated by default as identity (start with 1) primary key,
    name varchar(150) not null,
    address1 varchar(200) not null,
    address2 varchar(200) not null,
    phone varchar(20) not null,
    mobile varchar(20) not null,
    email varchar(20) not null,
    contactPerson1 varchar(150) not null,
    contactPhone1 varchar(20) not null,
    contactPerson2 varchar(150) not null,
    contactPhone2 varchar(20) not null,
    note varchar(500) not null,
    createdOn datetime not null,
    modifiedOn datetime,
    createdBy varchar(45) not null,
    modifiedBy varchar(45)
);

create table make (
   id integer generated by default as identity (start with 1) primary key,
   makeName varchar(45) not null,
   description varchar(200),
   createdOn datetime not null,
   modifiedOn datetime,
   createdBy varchar(45) not null,
   modifiedBy varchar(45)
 );

create table model (
    id integer generated by default as identity (start with 1) primary key,
    modelName varchar(145) not null,
    makeId integer not null,
    createdOn datetime not null,
    modifiedOn datetime,
    createdBy varchar(45) not null,
    modifiedBy varchar(45)
);

create table transaction (
    id integer generated by default as identity (start with 1) primary key,
    tagNo varchar(45),
    dateReported datetime not null,
    customerId integer not null,
    productCategory varchar(45) not null,
    makeId integer not null,
    modelId integer not null,
    serialNo varchar(45) not null,
    accessories varchar(200),
    complaintReported varchar(200),
    complaintDiagnosed varchar(200),
    engineerRemarks varchar(200),
    repairAction varchar(200),
    note varchar(500),
    status varchar(45) not null,
    createdOn datetime not null,
    modifiedOn datetime,
    createdBy varchar(45) not null,
    modifiedBy varchar(45)
);

create table invoice (
    id integer generated by default as identity (start with 1) primary key,
    transactionId varchar(45),
    description varchar(150) not null,
    serialNo varchar(150) not null,
    amount varchar(20) not null,
    quantity varchar(45),
    rate varchar(45),
    customerId integer not null,
    customerName varchar(45) not null,
    tagNo varchar(45),
    createdOn datetime not null,
    modifiedOn datetime,
    createdBy varchar(45) not null,
    modifiedBy varchar(45)
);


